### ISSUE TITLE
Client Lab

### ISSUE THREAD

**Issue by screenthong** [screenthong/SEBC#8]

**Comment by screenthong** [comment]
[root@ip-172-31-8-59 bin]# env |grep HUE
HUE_CONF_DIR=/var/run/cloudera-scm-agent/process/333-hue-HUE_SERVER


after run command 
/opt/cloudera/parcels/CDH/lib/hue/build/env/bin/hue useradmin_sync_with_unix


/var/run/cloudera-scm-agent/process/333-hue-HUE_SERVER/altscript.sh: line 12: /bin/java: No such file or directory
/var/run/cloudera-scm-agent/process/333-hue-HUE_SERVER/altscript.sh: line 12: exec: /bin/java: cannot execute: No such file or directory
Traceback (most recent call last):
  File "./hue", line 12, in <module>
    load_entry_point('desktop==3.9.0', 'console_scripts', 'hue')()
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/desktop/core/src/desktop/manage_entry.py", line 59, in entry
    execute_from_command_line(sys.argv)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/desktop/core/src/desktop/settings.py", line 328, in <module>
    "PASSWORD" : desktop.conf.get_database_password(),
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/desktop/core/src/desktop/conf.py", line 1278, in get_database_password
    password = DATABASE.PASSWORD_SCRIPT.get()
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/desktop/core/src/desktop/lib/conf.py", line 147, in get
    return self.config.get_value(data, present=present, prefix=self.prefix, coerce_type=True)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/desktop/core/src/desktop/lib/conf.py", line 263, in get_value
    return self._coerce_type(raw_val, prefix)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/desktop/core/src/desktop/lib/conf.py", line 283, in _coerce_type
    return self.type(raw)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/desktop/core/src/desktop/lib/conf.py", line 714, in coerce_password_from_script
    raise subprocess.CalledProcessError(p.returncode, script)
subprocess.CalledProcessError: Command '/var/run/cloudera-scm-agent/process/333-hue-HUE_SERVER/altscript.sh sec-5-password' returned non-zero exit status 126

**Comment by screenthong** [comment]
try
```
HUE_IGNORE_PASSWORD_SCRIPT_ERRORS=1 HUE_DATABASE_PASSWORD=hue /opt/cloudera/parcels/CDH/lib/hue/build/env/bin/hue useradmin_sync_with_unix
```

still error 

```
[root@ip-172-31-8-59 /]# HUE_IGNORE_PASSWORD_SCRIPT_ERRORS=1 HUE_DATABASE_PASSWORD=hue /opt/cloudera/parcels/CDH/lib/hue/build/env/bin/hue useradmin_sync_with_unix
/var/run/cloudera-scm-agent/process/333-hue-HUE_SERVER/altscript.sh: line 12: /bin/java: No such file or directory
/var/run/cloudera-scm-agent/process/333-hue-HUE_SERVER/altscript.sh: line 12: exec: /bin/java: cannot execute: No such file or directory
Traceback (most recent call last):
  File "/opt/cloudera/parcels/CDH/lib/hue/build/env/bin/hue", line 12, in <module>
    load_entry_point('desktop==3.9.0', 'console_scripts', 'hue')()
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/desktop/core/src/desktop/manage_entry.py", line 59, in entry
    execute_from_command_line(sys.argv)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/apps/useradmin/src/useradmin/management/commands/useradmin_sync_with_unix.py", line 47, in handle
    sync_unix_users_and_groups(min_uid, max_uid, min_gid, max_gid, check_shell)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/apps/useradmin/src/useradmin/views.py", line 688, in sync_unix_users_and_groups
    hue_group = Group.objects.get(name=name)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/models/sql/compiler.py", line 785, in execute_sql
    cursor = self.connection.cursor()
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/__init__.py", line 162, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/__init__.py", line 132, in _cursor
    self.ensure_connection()
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/__init__.py", line 115, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/mysql/base.py", line 435, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/MySQL_python-1.2.5-py2.6-linux-x86_64.egg/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p0.5/lib/hue/build/env/lib/python2.6/site-packages/MySQL_python-1.2.5-py2.6-linux-x86_64.egg/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'hue'@'ip-172-31-8-59.ap-southeast-1.compute.internal' (using password: YES)")
```

**Comment by screenthong** [comment]
reset passwd database hue in mysql server
```
grant all on hue.* to 'hue'@'%' identified by 'hue';
```
